"""init

Revision ID: aea894eb4292
Revises:
Create Date: 2022-09-26 12:58:56.664374

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'aea894eb4292'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'corp_auth',
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('corp_id', sa.String(), nullable=False),
        sa.Column('permanent_code', sa.String(), nullable=False),
        sa.Column('raw', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('corp_id', name='uq_suite_auth_corp_id'),
    )
    op.create_table(
        'dingding_user',
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nick', sa.String(), nullable=False),
        sa.Column('corp_id', sa.String(), nullable=False),
        sa.Column('open_id', sa.String(), nullable=False),
        sa.Column('union_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('avatar_url', sa.String(), nullable=True),
        sa.Column('mobile', sa.String(), nullable=True),
        sa.Column('staff_id', sa.String(), nullable=True),
        sa.Column('tenant_id', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('corp_id', 'user_id', name='uq_dingding_user_corp_id_union_id'),
    )
    op.create_table(
        'suite',
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('corp_id', sa.String(), nullable=False),
        sa.Column('suite_key', sa.String(), nullable=False),
        sa.Column('suite_ticket', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('corp_id', name='uq_suite_corp_id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suite')
    op.drop_table('dingding_user')
    op.drop_table('corp_auth')
    # ### end Alembic commands ###
